### ISSUE TITLE
Error: Content and Map of this Source is not available (only size() is supported)

### ISSUE THREAD

**Issue by steverandy** [axe312ger/gatsby-plugin-webpack-size#5]
```
"gatsby-plugin-webpack-size": "2.0.1"
"gatsby": "3.0.4"
```

Got the following error when building production assets.

```
Error: Content and Map of this Source is not available (only size() is supported)
at SizeOnlySource._error (node_modules/webpack/node_modules/webpack-sources/lib/SizeOnlySource.js:16:10)
at SizeOnlySource.source (node_modules/webpack/node_modules/webpack-sources/lib/SizeOnlySource.js:26:14)
at node_modules/size-plugin/dist/size-plugin.cjs:2989:96
at Array.map (<anonymous>)
at SizePlugin.outputSizes (node_modules/size-plugin/dist/size-plugin.cjs:2989:48)
```

**Comment by cameronbraid** [comment]
https://github.com/GoogleChromeLabs/size-plugin/issues/40
